apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: trip-viewer-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tripviewer.51-140-223-42.nip.io # IMPORTANT: update <ingress ip> with the dashed public IP of your ingress, for example frontend.13-68-177-68.nip.io
    http:
      paths:
      - backend:
          serviceName: tripviewer
          servicePort: 80
        path: /
