#for user profile api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofileapi
  namespace: api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofileapi
  template:
    metadata:
      labels:
        app: userprofileapi
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: userprofileapi
        image: acrplaywithk8.azurecr.io/up-api:v1
        imagePullPolicy: Always
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: upport
        volumeMounts:
        - name: secretmount
          mountPath: /secrets
          readOnly: true
      volumes:
          - name: secretmount
            secret:
              secretName: secrets-store-creds    
---
apiVersion: v1
kind: Service
metadata:
  name: userprofileapi
  namespace: api-dev
spec:
  ports:
  - port: 80
  selector:
    app: userprofileapi
---
#end for user profile api