#for user profile java
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofilejava
  namespace: api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofilejava
  template:
    metadata:
      labels:
        app: userprofilejava
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: userprofilejava
        image: acrplaywithk8.azurecr.io/upjava-api:v1
        imagePullPolicy: Always
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: ujport
        volumeMounts:
        - name: secretmount
          mountPath: /secrets
          readOnly: true
      volumes:
          - name: secretmount
            secret:
              secretName: secrets-store-creds    
---
apiVersion: v1
kind: Service
metadata:
  name: userprofilejava
  namespace: api-dev
spec:
  ports:
  - port: 80
  selector:
    app: userprofilejava
---
#end for user profile java